import { afterEach, describe, expect, it, vi } from 'vitest';
import { createCatalogRegistry, createMessageFormatter, createTranslator } from '@etyma/core';
import { i18n, type BlogI18n, type MessageKey, type Translate } from '../../src/i18n';
import contract from '../../src/i18n/etyma.generated';
import { getOgLocale } from '../../src/i18n/og-locale';
import { catalogUrl, I18N_PROJECT } from '../../src/i18n/project';

// Locale-routing behavior (Astro's native `i18n` config, `/ua` -> `uk`,
// localized paths, canonical/hreflang/x-default, language dropdown) is
// exercised against the real production build in tests/e2e — @etyma/astro
// already unit-tests that logic itself, so it is not duplicated here.
//
// Production translations live in Glossa and are read at build time. These tests
// never touch the network: `fetch` is stubbed and serves a tiny synthetic catalog
// per locale — not a copy of the production content.

const GLOSSA = 'https://glossa.andersseen.dev/i18n/my-blog';

const FIXTURES: Record<string, Record<string, unknown>> = {
  es: {
    nav: { home: 'Inicio', blog: 'Blog' },
    post: {
      title: 'Publicación: {$title}',
      since: 'Desde {$year :number useGrouping=never}',
    },
  },
  // Deliberately partial: `nav.blog` and `post.*` must fall back to the source locale.
  en: { nav: { home: 'Home' } },
  uk: { nav: { home: 'Головна' } },
};

const stubGlossa = () => {
  const fetchMock = vi.fn(async (input: string | URL | Request) => {
    const url = String(input);
    const locale = url.slice(`${GLOSSA}/`.length).replace(/\.json$/, '');
    const body = FIXTURES[locale];
    return body
      ? new Response(JSON.stringify(body), { status: 200 })
      : new Response('not found', { status: 404 });
  });
  vi.stubGlobal('fetch', fetchMock);
  return fetchMock;
};

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('Etyma i18n definition', () => {
  it('uses real BCP-47 language codes, never the "ua" URL path', () => {
    expect(i18n.locales).toEqual(['es', 'en', 'uk']);
    expect(i18n.locales).not.toContain('ua');
  });

  it('uses Spanish as the source locale, matching the Glossa project and Astro default', () => {
    expect(i18n.sourceLocale).toBe('es');
  });

  it('takes its locales and source locale from the single i18n project constant', () => {
    expect(i18n.locales).toEqual([...I18N_PROJECT.locales]);
    expect(i18n.sourceLocale).toBe(I18N_PROJECT.sourceLocale);
  });

  it('resolves every catalog URL from one {locale} template', () => {
    expect(I18N_PROJECT.remote).toBe(`${GLOSSA}/{locale}.json`);
    expect(I18N_PROJECT.locales.map(catalogUrl)).toEqual([
      `${GLOSSA}/es.json`,
      `${GLOSSA}/en.json`,
      `${GLOSSA}/uk.json`,
    ]);
  });

  it('exposes the generated key contract as typed, dotted keys', () => {
    expect(i18n.keys.length).toBeGreaterThan(0);
    expect(i18n.keys).toContain('nav.home');
    expect(i18n.keys).toContain('footer.rights');
    expect(i18n.keys).toContain('blog.heroImageAlt');
    expect(i18n.keys).toContain('language.uk');
  });

  it('rejects unknown translation keys at compile time', () => {
    // Enforced by `astro check` (tests are part of the tsconfig program): if
    // `MessageKey` ever widened to `string`, the directive below would itself error.
    const known: MessageKey = 'nav.home';
    // @ts-expect-error — not a key in the Glossa source catalog contract
    const unknown: MessageKey = 'nav.doesNotExist';

    expect(known).toBe('nav.home');
    expect(unknown).toBe('nav.doesNotExist');
  });
});

describe('generated contract params, through the Astro types', () => {
  // The committed contract is the Glossa source catalog's, regenerated by
  // etymaRemoteContract on every build — the assertions below track production messages.
  it('carries the variables and MF2 functions of the parameterized source messages', () => {
    expect(contract.variables).toEqual({
      'blog.heroImageAlt': ['title'],
      'blogPost.heroImageAlt': ['title'],
      'footer.rights': ['author', 'year'],
    });
    expect(contract.functions).toEqual({ 'footer.rights': { year: ['number'] } });
  });

  // Type-only: never called. `astro check` (which includes tests) enforces every
  // directive, so a `Translate` that stopped seeing params would make them unused errors.
  const translateChecks = (t: Translate) => {
    t('nav.home');
    // @ts-expect-error — not a key in the Glossa source catalog contract
    t('nav.doesNotExist');

    t('blog.heroImageAlt', { title: 'Example' });
    // @ts-expect-error — `blog.heroImageAlt` declares {$title}, so params are required
    t('blog.heroImageAlt');
    // @ts-expect-error — misspelled variable name
    t('blog.heroImageAlt', { titel: 'Example' });

    t('footer.rights', { year: 2026, author: 'Andrii' });
    // @ts-expect-error — `author` is a declared variable of footer.rights
    t('footer.rights', { year: 2026 });
    // @ts-expect-error — {$year :number} accepts a numeric value, not a Date
    t('footer.rights', { year: new Date(), author: 'Andrii' });
  };

  // The presentational boundary: components receive `t: Translate` as a prop
  // (Footer.astro, SkipLink.astro, ...) or the whole `etyma: BlogI18n` (Header.astro, ...).
  interface FooterLikeProps {
    t: Translate;
  }
  const componentPropChecks = ({ t }: FooterLikeProps, etyma: BlogI18n) => {
    t('footer.rights', { year: 2026, author: 'Andrii' });
    // @ts-expect-error — the prop keeps the per-key param contract
    t('footer.rights', { year: new Date(), author: 'Andrii' });

    etyma.t('blogPost.heroImageAlt', { title: 'Example' });
    // @ts-expect-error — the whole Etyma object keeps it too
    etyma.t('blogPost.heroImageAlt');
    etyma.parts('blog.heroImageAlt', { title: 'Example' });
    // @ts-expect-error — and so does parts()
    etyma.parts('blog.heroImageAlt', { titel: 'Example' });
  };

  it('keeps per-key param checks on Translate and BlogI18n (enforced by astro check)', () => {
    expect(translateChecks).toBeTypeOf('function');
    expect(componentPropChecks).toBeTypeOf('function');
  });
});

describe('remote loading from Glossa Public Delivery', () => {
  it('has no synchronous source catalog: every locale, source included, is fetched', () => {
    expect(i18n.sourceCatalog).toBeUndefined();
    for (const locale of ['en', 'es', 'uk']) {
      expect(i18n.loaderFor(locale)).toBeTypeOf('function');
    }
  });

  it('requests exactly one Glossa catalog URL per locale (uk, not ua)', async () => {
    const fetchMock = stubGlossa();
    const registry = createCatalogRegistry(i18n);

    await Promise.all(['en', 'es', 'uk'].map(locale => registry.load(locale)));

    expect(fetchMock.mock.calls.map(([url]) => String(url)).sort()).toEqual([
      `${GLOSSA}/en.json`,
      `${GLOSSA}/es.json`,
      `${GLOSSA}/uk.json`,
    ]);
  });

  it('fails loudly, rather than rendering empty text, when a catalog is unavailable', async () => {
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => new Response('down', { status: 503 })),
    );
    const registry = createCatalogRegistry(i18n);

    await expect(registry.load('es')).rejects.toThrow();
  });

  it('translates from the loaded locale and falls back to the source locale', async () => {
    stubGlossa();
    const registry = createCatalogRegistry(i18n);
    const [es, en] = await Promise.all([registry.load('es'), registry.load('en')]);
    const translate = createTranslator({
      locale: 'en',
      catalog: en,
      sourceLocale: i18n.sourceLocale,
      sourceCatalog: es,
      formatter: createMessageFormatter(),
    });

    expect(translate.translate('nav.home')).toBe('Home');
    expect(translate.translate('nav.blog')).toBe('Blog'); // absent in en -> source (es)
  });

  it('renders MessageFormat 2 placeholders and number formatting', async () => {
    stubGlossa();
    const registry = createCatalogRegistry(i18n);
    const es = await registry.load('es');
    const translate = createTranslator({
      locale: 'es',
      catalog: es,
      sourceLocale: i18n.sourceLocale,
      sourceCatalog: es,
      formatter: createMessageFormatter(),
    });

    expect(translate.translate('post.title', { title: 'Hello' }).replace(/[⁨⁩]/g, '')).toBe(
      'Publicación: Hello',
    );
    expect(translate.translate('post.since', { year: 2026 }).replace(/[⁨⁩]/g, '')).toBe(
      'Desde 2026',
    );
  });
});

describe('getOgLocale', () => {
  it('maps real locale codes to Open Graph underscore locales', () => {
    expect(getOgLocale('es')).toBe('es_ES');
    expect(getOgLocale('en')).toBe('en_US');
    expect(getOgLocale('uk')).toBe('uk_UA');
  });

  it('falls back to the source locale (Spanish) for an unknown locale', () => {
    expect(getOgLocale('fr')).toBe('es_ES');
  });
});
